Fix touch scrolling snapping sheet
DHBW-FN-TIT20/know-where-you-go pull request #48
Opened 2023-01-03 23:26 UTC by johannesbrandenburger

Bitte auch auf anderen Geräten testen als iPhone.

2023-01-03 23:27 UTC, johannesbrandenburger commented
lost mal wieder auf main gemacht

2023-01-04 12:19 UTC, schuler-henry reviewed
Kleine Anmerkungen sin dim Code.
Ausgetestet habe ich jetzt nicht, kann ich aber später noch machen.
Dazu wäre es ganz hilfreich, wenn du (@johannesbrandenburger) den Bug nochmal kurz in nem Kommentar beschreiben könntest, dass das mit dem Pull Request verlinkt ist (Oder gibts dazu was im Jira das ich nicht sehe?).
Es ist sonst schwierig zu testen wenn man nicht weiß was genau xD.

2023-01-04 12:19 UTC, schuler-henry commented on src/components/SnappingSheet.jsx
> +    // prevent default if this.currentState !== this.props.snapHeightStates.length - 1
Der Kommentar ist praktisch genau das was im if steht.
Ersetz den Kommentar lieber durch ne kurze Erklärung **warum** genau dann `event.preventDefault()` benötigt wird.

2023-01-04 12:19 UTC, schuler-henry commented on src/components/SnappingSheet.jsx
> +    if (newSheetHeight > this.props.snapHeightStates[this.props.snapHeightStates.length - 1]) {
Wäre hier `else if` performanter?

2023-01-04 12:19 UTC, schuler-henry commented on src/components/SnappingSheet.jsx
> +    this.setState({ sheetHeight: newSheetHeight });
und wäre das hier dann ein `else`?

2023-01-04 12:21 UTC, johannesbrandenburger commented
Der Bug war, dass man auf mobile nicht scrollen konnte im Content des Sheet Modals.

2023-01-04 12:23 UTC, johannesbrandenburger commented on src/components/SnappingSheet.jsx
> +    if (newSheetHeight > this.props.snapHeightStates[this.props.snapHeightStates.length - 1]) {
Nein. Und (meiner Meinung) nach schlechter lesbar.

2023-01-04 12:24 UTC, johannesbrandenburger commented on src/components/SnappingSheet.jsx
> +    this.setState({ sheetHeight: newSheetHeight });
Wenn davor ein `return` steht, macht man das nicht.

2023-01-04 12:25 UTC, johannesbrandenburger commented on src/components/SnappingSheet.jsx
> +    // prevent default if this.currentState !== this.props.snapHeightStates.length - 1
Hast Recht mach ich gleich 👍

2023-01-04 12:33 UTC, schuler-henry commented on src/components/SnappingSheet.jsx
> +    this.setState({ sheetHeight: newSheetHeight });
Ja gut, das wäre nur im Zusammenhang mit dem else if.
Klar braucht man das nach nem return nicht. Den hab ich wohl überlesen, mein Fehler.

2023-01-04 12:34 UTC, johannesbrandenburger commented on src/components/SnappingSheet.jsx
> +    this.setState({ sheetHeight: newSheetHeight });
Alles klar. Wenn's sonst jetzt passt, kannst du gern mergen.

2023-01-04 12:46 UTC, Floskinner approved these changes
Also bei mir ist der Bug gefixed (iPhone)

2023-01-04 12:47 UTC, schuler-henry commented
Habs jetzt mal im lokalen dev auf Android 12 getestet.
Scrolling durch die Wiki Infos klappt wenn das Modal ganz ausgefahren ist.
Was nicht klappt ist das Scrolling wenn es im unteren State ist.
Ich verstehe, dass das aus dem Grund nicht gewollt ist, dass man so leichter das Menü nach oben verschieben kann, ist aber design-technisch finde ich unglücklich.

Man kann zum Beispiel auch wenn es ganz ausgefahren ist scrollen, und wenn man das Fenster dann wieder verkleinert, bleibt es irgend wo in der mitte gescrollt, man kann aber nicht mehr scrollen.

2023-01-04 12:47 UTC, schuler-henry requested changes
Siehe Kommentar

2023-01-04 12:53 UTC, johannesbrandenburger commented
> Habs jetzt mal im lokalen dev auf Android 12 getestet. Scrolling durch die Wiki Infos klappt wenn das Modal ganz ausgefahren ist. Was nicht klappt ist das Scrolling wenn es im unteren State ist. Ich verstehe, dass das aus dem Grund nicht gewollt ist, dass man so leichter das Menü nach oben verschieben kann, ist aber design-technisch finde ich unglücklich.
> 
> Man kann zum Beispiel auch wenn es ganz ausgefahren ist scrollen, und wenn man das Fenster dann wieder verkleinert, bleibt es irgend wo in der mitte gescrollt, man kann aber nicht mehr scrollen.

Also Glaser und ich finden es so wie es jetzt ist besser. Können wir aber gerne für den nächsten Sprint in der Gruppe beraten.

2023-01-04 12:53 UTC, schuler-henry commented
Als Lösung wäre denkbar, dass wie auch z.B. bei Google Maps nur Ort und Distanz angezeigt werden im ersten State und die Wiki Info nur ganz ausgefahren.
Das diese zwei Teile quasi getrennt sind und die Scrollable Wiki-Info ausschließlich im ausgefahrenen State angezeigt wird.

2023-01-04 12:58 UTC, schuler-henry approved these changes

2023-01-04 13:09 UTC, johannesbrandenburger commented
ist gemacht

2023-01-04 13:09 UTC, merged